{% set name = "schema" %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce0186666940271e5faeb31b92c830aab6e7eb3f0d6feb88a107a76bba964ba7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - contextlib2 >=0.5.5

test:
  requires:
    - pip
  imports:
    - schema
  commands:
    - pip check

about:
  home: https://github.com/keleshev/schema
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Schema validation just got Pythonic

  description: |
    schema is a Python library for validating data structures, such as those
    obtained from config-files, forms, external services or command-line
    parsing, converted from JSON/YAML (or something else) to Python data-types.
  dev_url: https://github.com/keleshev/schema

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
    - maxhora
